
### FIND ALL SONG
GET http://localhost:3000/songs

### FIND SONG
GET http://localhost:3000/songs/1

### CREATE NEW SONG
POST  http://localhost:3000/songs
# Content-Type: application/json

# {
#   releasedDate: "2024-09-29",
#   duration: "3:38"
# }

### UPDATE SONG
PUT  http://localhost:3000/songs/1

### DELETE SONG
DELETE  http://localhost:3000/songs/1